# Generated by Django 4.2.1 on 2023-05-16 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("photos", models.ImageField(upload_to="photos/")),
                ("headline", models.CharField(default="coming soon", max_length=1000)),
                ("date_field", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
